package dev.banking.asyncapi.generator.core.generator.kotlin.kafka.spring

import dev.banking.asyncapi.generator.core.generator.util.FileUtil
import java.io.File

class KotlinSpringKafkaMessageGenerator(
    private val outputDir: File,
    private val packageName: String,
) {
    fun generate() {
        val content = """
               package $packageName

               /**
                * Wrapper for Kafka message payload and metadata.
                * Generated by asyncapi-generator.
                */
               data class KafkaMessage<T>(
                   val payload: T,
                   val key: String?,
                   val headers: Map<String, Any>,
                   val topic: String,
                   val partition: Int,
                   val offset: Long,
                   val timestamp: Long
               )
           """.trimIndent()

        val packageDir = FileUtil.packageDirectory(outputDir, packageName)
        val outputFile = File(packageDir, "KafkaMessage.kt")
        outputFile.parentFile.mkdirs()
        outputFile.writeText(content)
    }
}
