package dev.banking.asyncapi.generator.core.generator.java.kafka.spring

import dev.banking.asyncapi.generator.core.generator.util.FileUtil
import java.io.File

class JavaSpringKafkaMessageGenerator(
    private val outputDir: File,
    private val packageName: String,
) {
    fun generate() {
        val content = """
               package $packageName;

               import java.util.Map;

               /**
                * Wrapper for Kafka message payload and metadata.
                * Generated by asyncapi-generator.
                *
                * @param <T> The type of the payload.
                */
               public class KafkaMessage<T> {
                   private final T payload;
                   private final String key;
                   private final Map<String, Object> headers;
                   private final String topic;
                   private final int partition;
                   private final long offset;
                   private final long timestamp;

                   public KafkaMessage(T payload, String key, Map<String, Object> headers, String topic, int partition, long offset, long timestamp) {
                       this.payload = payload;
                       this.key = key;
                       this.headers = headers;
                       this.topic = topic;
                       this.partition = partition;
                       this.offset = offset;
                       this.timestamp = timestamp;
                   }

                   public T getPayload() { return payload; }
                   public String getKey() { return key; }
                   public Map<String, Object> getHeaders() { return headers; }
                   public String getTopic() { return topic; }
                   public int getPartition() { return partition; }
                   public long getOffset() { return offset; }
                   public long getTimestamp() { return timestamp; }
               }
           """.trimIndent()

        val packageDir = FileUtil.packageDirectory(outputDir, packageName)
        val file = File(packageDir, "KafkaMessage.java")
        file.writeText(content)
    }
}
