package dev.banking.asyncapi.generator.core.model.validator

import dev.banking.asyncapi.generator.core.model.validator.ValidationConcern.ADVISORY
import dev.banking.asyncapi.generator.core.model.validator.ValidationConcern.GENERATOR_CAPABILITY
import dev.banking.asyncapi.generator.core.model.validator.ValidationConcern.SPECIFICATION
import dev.banking.asyncapi.generator.core.model.validator.ValidationSeverity.ERROR
import dev.banking.asyncapi.generator.core.model.validator.ValidationSeverity.WARNING

private const val ASYNCAPI_SPEC = "https://www.asyncapi.com/docs/reference/specification/v3.0.0"
private const val ASYNCAPI_SCHEMA = "$ASYNCAPI_SPEC#schemaObject"
private const val JSON_SCHEMA = "https://json-schema.org/draft-07/draft-handrews-json-schema-validation-01"
private const val PROJECT_RULES =
    "https://github.com/evryfs/asyncapi-generator/blob/main/docs/validator/rules.md"

/** Stable identity and ownership metadata for a validation rule. */
enum class ValidationRule(
    val code: String,
    val concern: ValidationConcern,
    val severity: ValidationSeverity,
    val documentation: String,
) {
    DOCUMENT_ID_FORMAT("AAS3-DOCUMENT-ID-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    DOCUMENT_ID_URN_RECOMMENDED("ADV-DOCUMENT-ID-URN", ADVISORY, WARNING, PROJECT_RULES),
    DOCUMENT_DEFAULT_CONTENT_TYPE_FORMAT("AAS3-DOCUMENT-CONTENT-TYPE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),

    INFO_TITLE_REQUIRED("AAS3-INFO-TITLE-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    INFO_VERSION_REQUIRED("AAS3-INFO-VERSION-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    INFO_VERSION_FORMAT("ADV-INFO-VERSION-FORMAT", ADVISORY, WARNING, PROJECT_RULES),
    INFO_TERMS_OF_SERVICE_FORMAT("AAS3-INFO-TERMS-URI", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CONTACT_EMPTY("ADV-CONTACT-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    CONTACT_URL_FORMAT("AAS3-CONTACT-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CONTACT_EMAIL_FORMAT("AAS3-CONTACT-EMAIL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    LICENSE_NAME_REQUIRED("AAS3-LICENSE-NAME-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    LICENSE_URL_FORMAT("AAS3-LICENSE-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),

    SERVER_HOST_REQUIRED("AAS3-SERVER-HOST-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SERVER_NAME_FORMAT("AAS3-SERVER-NAME-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SERVER_HOST_CONTAINS_PROTOCOL("ADV-SERVER-HOST-PROTOCOL", ADVISORY, WARNING, PROJECT_RULES),
    SERVER_VARIABLE_UNDEFINED("AAS3-SERVER-VARIABLE-UNDEFINED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SERVER_PROTOCOL_REQUIRED("AAS3-SERVER-PROTOCOL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SERVER_VARIABLE_ENUM_UNIQUE("AAS3-SERVER-VARIABLE-ENUM-UNIQUE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SERVER_VARIABLE_DEFAULT_ENUM("ADV-SERVER-VARIABLE-DEFAULT-ENUM", ADVISORY, WARNING, PROJECT_RULES),
    SERVER_VARIABLE_EXAMPLES_EMPTY("ADV-SERVER-VARIABLE-EXAMPLES-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    SERVER_VARIABLE_EXAMPLES_ENUM("ADV-SERVER-VARIABLE-EXAMPLES-ENUM", ADVISORY, WARNING, PROJECT_RULES),

    CHANNEL_ADDRESS_QUERY_OR_FRAGMENT("AAS3-CHANNEL-ADDRESS-SUFFIX", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CHANNEL_PARAMETER_UNDEFINED("AAS3-CHANNEL-PARAMETER-UNDEFINED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CHANNEL_PARAMETER_UNUSED("AAS3-CHANNEL-PARAMETER-UNUSED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CHANNEL_SERVERS_EMPTY("ADV-CHANNEL-SERVERS-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    CHANNEL_MESSAGES_AMBIGUOUS("GEN-CHANNEL-MESSAGES-AMBIGUOUS", GENERATOR_CAPABILITY, WARNING, PROJECT_RULES),
    CHANNEL_BINDINGS_EMPTY("ADV-CHANNEL-BINDINGS-EMPTY", ADVISORY, WARNING, PROJECT_RULES),

    PARAMETER_ENUM_UNIQUE("AAS3-PARAMETER-ENUM-UNIQUE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    PARAMETER_NAME_FORMAT("AAS3-PARAMETER-NAME-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    PARAMETER_DEFAULT_ENUM("ADV-PARAMETER-DEFAULT-ENUM", ADVISORY, WARNING, PROJECT_RULES),
    PARAMETER_EXAMPLES_ENUM("ADV-PARAMETER-EXAMPLES-ENUM", ADVISORY, WARNING, PROJECT_RULES),
    PARAMETER_LOCATION_FORMAT("AAS3-PARAMETER-LOCATION", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CORRELATION_LOCATION_REQUIRED("AAS3-CORRELATION-LOCATION-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    CORRELATION_LOCATION_FORMAT("AAS3-CORRELATION-LOCATION-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    EXTERNAL_DOC_URL_REQUIRED("AAS3-EXTERNAL-DOC-URL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    EXTERNAL_DOC_URL_FORMAT("AAS3-EXTERNAL-DOC-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    TAG_NAME_REQUIRED("AAS3-TAG-NAME-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),

    MESSAGE_TRAIT_EMPTY("ADV-MESSAGE-TRAIT-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    MESSAGE_CONTENT_TYPE_FORMAT("AAS3-MESSAGE-CONTENT-TYPE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    MESSAGE_EXAMPLE_CONTENT_REQUIRED("AAS3-MESSAGE-EXAMPLE-CONTENT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    MESSAGE_HEADER_FORMAT_UNSUPPORTED("GEN-MESSAGE-HEADER-FORMAT", GENERATOR_CAPABILITY, WARNING, PROJECT_RULES),

    OPERATION_ACTION_REQUIRED("AAS3-OPERATION-ACTION-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_ACTION_VALUE("AAS3-OPERATION-ACTION-VALUE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_CHANNEL_REQUIRED("AAS3-OPERATION-CHANNEL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_CHANNEL_TARGET("AAS3-OPERATION-CHANNEL-TARGET", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_CHANNEL_REFERENCE_SCOPE("AAS3-OPERATION-CHANNEL-SCOPE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_MESSAGE_REFERENCE("AAS3-OPERATION-MESSAGE-REFERENCE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_TRAIT_EMPTY("ADV-OPERATION-TRAIT-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    OPERATION_REPLY_MESSAGES_EMPTY("ADV-OPERATION-REPLY-MESSAGES-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    OPERATION_REPLY_CHANNEL_REQUIRED("AAS3-REPLY-CHANNEL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_REPLY_CHANNEL_REFERENCE("AAS3-REPLY-CHANNEL-SCOPE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_REPLY_CHANNEL_ADDRESS("AAS3-REPLY-CHANNEL-ADDRESS", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_REPLY_MESSAGE_REFERENCE("AAS3-REPLY-MESSAGE-REFERENCE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_REPLY_ADDRESS_REQUIRED("AAS3-REPLY-ADDRESS-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    OPERATION_REPLY_ADDRESS_FORMAT("AAS3-REPLY-ADDRESS-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),

    SECURITY_TYPE_REQUIRED("AAS3-SECURITY-TYPE-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_TYPE_VALUE("AAS3-SECURITY-TYPE-VALUE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_NAME_REQUIRED("AAS3-SECURITY-NAME-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_IN_REQUIRED("AAS3-SECURITY-IN-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_IN_VALUE("AAS3-SECURITY-IN-VALUE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_SCHEME_REQUIRED("AAS3-SECURITY-SCHEME-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_FLOWS_REQUIRED("AAS3-SECURITY-OAUTH-FLOWS", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_AUTHORIZATION_URL_REQUIRED("AAS3-OAUTH-AUTHORIZATION-URL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_AUTHORIZATION_URL_FORMAT("AAS3-OAUTH-AUTHORIZATION-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_TOKEN_URL_REQUIRED("AAS3-OAUTH-TOKEN-URL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_TOKEN_URL_FORMAT("AAS3-OAUTH-TOKEN-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_REFRESH_URL_FORMAT("AAS3-OAUTH-REFRESH-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_AVAILABLE_SCOPES_REQUIRED("AAS3-OAUTH-AVAILABLE-SCOPES-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OAUTH_SCOPE_AVAILABLE("AAS3-OAUTH-SCOPE-AVAILABLE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OPEN_ID_URL_REQUIRED("AAS3-SECURITY-OPENID-URL-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    SECURITY_OPEN_ID_URL_FORMAT("AAS3-SECURITY-OPENID-URL-FORMAT", SPECIFICATION, ERROR, ASYNCAPI_SPEC),

    BINDING_EMPTY("ADV-BINDING-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    BINDING_PROTOCOL_NULL("ADV-BINDING-PROTOCOL-NULL", ADVISORY, WARNING, PROJECT_RULES),
    BINDING_PROTOCOL_TYPE("AAS3-BINDING-PROTOCOL-TYPE", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    BINDING_PROPERTY_NULL("ADV-BINDING-PROPERTY-NULL", ADVISORY, WARNING, PROJECT_RULES),
    BINDING_PROPERTY_LIST("GEN-BINDING-PROPERTY-LIST", GENERATOR_CAPABILITY, WARNING, PROJECT_RULES),
    BINDING_PROPERTY_EMPTY("ADV-BINDING-PROPERTY-EMPTY", ADVISORY, WARNING, PROJECT_RULES),
    BINDING_PROPERTY_TYPE("GEN-BINDING-PROPERTY-TYPE", GENERATOR_CAPABILITY, WARNING, PROJECT_RULES),

    REFERENCE_UNRESOLVED("AAS3-REFERENCE-UNRESOLVED", SPECIFICATION, ERROR, ASYNCAPI_SPEC),
    REFERENCE_CATEGORY_REQUIRED("GEN-REFERENCE-CATEGORY-REQUIRED", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    REFERENCE_TARGET_CATEGORY("AAS3-REFERENCE-TARGET-CATEGORY", SPECIFICATION, ERROR, ASYNCAPI_SPEC),

    SCHEMA_KEYWORD_UNSUPPORTED("GEN-SCHEMA-KEYWORD-UNSUPPORTED", GENERATOR_CAPABILITY, ERROR, ASYNCAPI_SCHEMA),
    SCHEMA_ANNOTATION_IGNORED("GEN-SCHEMA-ANNOTATION-IGNORED", GENERATOR_CAPABILITY, WARNING, ASYNCAPI_SCHEMA),
    SCHEMA_ITEMS_REPRESENTATION("GEN-SCHEMA-ITEMS-REPRESENTATION", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_DEPENDENCY_ARRAY_ITEMS("JSONSCHEMA-DEPENDENCY-ARRAY-ITEMS", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_DEPENDENCY_ARRAY_NONEMPTY("JSONSCHEMA-DEPENDENCY-ARRAY-NONEMPTY", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_DEPENDENCY_ARRAY_UNIQUE("JSONSCHEMA-DEPENDENCY-ARRAY-UNIQUE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_EXCLUSIVE_BOUND_TYPE("JSONSCHEMA-EXCLUSIVE-BOUND-TYPE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_DISCRIMINATOR_TYPE("AAS3-SCHEMA-DISCRIMINATOR-TYPE", SPECIFICATION, ERROR, ASYNCAPI_SCHEMA),
    SCHEMA_DIALECT("GEN-SCHEMA-DIALECT", GENERATOR_CAPABILITY, ERROR, JSON_SCHEMA),
    SCHEMA_TYPE("JSONSCHEMA-TYPE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_TYPE_ARRAY_NONEMPTY("JSONSCHEMA-TYPE-ARRAY-NONEMPTY", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_TYPE_ARRAY_UNIQUE("JSONSCHEMA-TYPE-ARRAY-UNIQUE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_ENUM_EMPTY("JSONSCHEMA-ENUM-NONEMPTY", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_ENUM_UNIQUE("JSONSCHEMA-ENUM-UNIQUE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_UNTYPED_ENUM("GEN-SCHEMA-UNTYPED-ENUM", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_CONST_TYPE("GEN-SCHEMA-CONST-TYPE", GENERATOR_CAPABILITY, ERROR, JSON_SCHEMA),
    SCHEMA_NUMERIC_RANGE("GEN-SCHEMA-NUMERIC-RANGE", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_MULTIPLE_OF("JSONSCHEMA-MULTIPLE-OF", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_STRING_LENGTH("JSONSCHEMA-STRING-LENGTH", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_STRING_LENGTH_RANGE("GEN-SCHEMA-STRING-LENGTH-RANGE", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_PATTERN("GEN-SCHEMA-PATTERN", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_ARRAY_SIZE("JSONSCHEMA-ARRAY-SIZE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_ARRAY_SIZE_RANGE("GEN-SCHEMA-ARRAY-SIZE-RANGE", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_OBJECT_SIZE("JSONSCHEMA-OBJECT-SIZE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_OBJECT_SIZE_RANGE("GEN-SCHEMA-OBJECT-SIZE-RANGE", GENERATOR_CAPABILITY, ERROR, PROJECT_RULES),
    SCHEMA_REQUIRED_EMPTY("ADV-SCHEMA-REQUIRED-EMPTY", ADVISORY, WARNING, JSON_SCHEMA),
    SCHEMA_REQUIRED_UNIQUE("JSONSCHEMA-REQUIRED-UNIQUE", SPECIFICATION, ERROR, JSON_SCHEMA),
    SCHEMA_REQUIRED_UNDECLARED("GEN-SCHEMA-REQUIRED-UNDECLARED", GENERATOR_CAPABILITY, WARNING, JSON_SCHEMA),
    SCHEMA_DEFAULT_TYPE("GEN-SCHEMA-DEFAULT-TYPE", GENERATOR_CAPABILITY, ERROR, JSON_SCHEMA),
    SCHEMA_DISCRIMINATOR_REQUIRED("AAS3-SCHEMA-DISCRIMINATOR-REQUIRED", SPECIFICATION, ERROR, ASYNCAPI_SCHEMA),
    SCHEMA_DISCRIMINATOR_PROPERTY("AAS3-SCHEMA-DISCRIMINATOR-PROPERTY", SPECIFICATION, ERROR, ASYNCAPI_SCHEMA),
    ;
}
