package dev.banking.asyncapi.generator.core.parser.version

/** Ordinary fixed-field AsyncAPI objects whose members are profile-owned. */
internal enum class AsyncApiObjectType(
    val displayName: String,
) {
    ASYNC_API("AsyncAPI Object"),
    INFO("Info Object"),
    CONTACT("Contact Object"),
    LICENSE("License Object"),
    SERVER("Server Object"),
    SERVER_VARIABLE("Server Variable Object"),
    CHANNEL("Channel Object"),
    PARAMETER("Parameter Object"),
    CORRELATION_ID("Correlation ID Object"),
    EXTERNAL_DOCUMENTATION("External Documentation Object"),
    TAG("Tag Object"),
    MESSAGE("Message Object"),
    MESSAGE_TRAIT("Message Trait Object"),
    MESSAGE_EXAMPLE("Message Example Object"),
    OPERATION("Operation Object"),
    OPERATION_TRAIT("Operation Trait Object"),
    OPERATION_REPLY("Operation Reply Object"),
    OPERATION_REPLY_ADDRESS("Operation Reply Address Object"),
    COMPONENTS("Components Object"),
    MULTI_FORMAT_SCHEMA("Multi Format Schema Object"),
    SECURITY_SCHEME("Security Scheme Object"),
    OAUTH_FLOWS("OAuth Flows Object"),
    OAUTH_FLOW("OAuth Flow Object"),
}

/** Returns the fixed-member contract implemented by this parser profile. */
internal fun AsyncApiParserProfile.allowedMembers(objectType: AsyncApiObjectType): Set<String> =
    when (this) {
        AsyncApiParserProfile.V3_0 -> V3_0_OBJECT_MEMBERS.getValue(objectType)
    }

private fun members(vararg names: String): Set<String> = names.toSet()

private val V3_0_OBJECT_MEMBERS: Map<AsyncApiObjectType, Set<String>> =
    mapOf(
        AsyncApiObjectType.ASYNC_API to members(
            "asyncapi",
            "id",
            "info",
            "servers",
            "defaultContentType",
            "channels",
            "operations",
            "components",
        ),
        AsyncApiObjectType.INFO to members(
            "title",
            "version",
            "description",
            "termsOfService",
            "contact",
            "license",
            "tags",
            "externalDocs",
        ),
        AsyncApiObjectType.CONTACT to members("name", "url", "email"),
        AsyncApiObjectType.LICENSE to members("name", "url"),
        AsyncApiObjectType.SERVER to members(
            "host",
            "protocol",
            "protocolVersion",
            "pathname",
            "description",
            "title",
            "summary",
            "variables",
            "security",
            "bindings",
            "tags",
            "externalDocs",
        ),
        AsyncApiObjectType.SERVER_VARIABLE to members("enum", "default", "description", "examples"),
        AsyncApiObjectType.CHANNEL to members(
            "address",
            "messages",
            "title",
            "summary",
            "description",
            "servers",
            "parameters",
            "tags",
            "externalDocs",
            "bindings",
        ),
        AsyncApiObjectType.PARAMETER to members("enum", "default", "description", "examples", "location"),
        AsyncApiObjectType.CORRELATION_ID to members("description", "location"),
        AsyncApiObjectType.EXTERNAL_DOCUMENTATION to members("description", "url"),
        AsyncApiObjectType.TAG to members("name", "description", "externalDocs"),
        AsyncApiObjectType.MESSAGE to members(
            "headers",
            "payload",
            "correlationId",
            "contentType",
            "name",
            "title",
            "summary",
            "description",
            "tags",
            "externalDocs",
            "bindings",
            "examples",
            "traits",
        ),
        AsyncApiObjectType.MESSAGE_TRAIT to members(
            "headers",
            "correlationId",
            "contentType",
            "name",
            "title",
            "summary",
            "description",
            "tags",
            "externalDocs",
            "bindings",
            "examples",
        ),
        AsyncApiObjectType.MESSAGE_EXAMPLE to members("headers", "payload", "name", "summary"),
        AsyncApiObjectType.OPERATION to members(
            "action",
            "channel",
            "title",
            "summary",
            "description",
            "security",
            "tags",
            "externalDocs",
            "bindings",
            "traits",
            "messages",
            "reply",
        ),
        AsyncApiObjectType.OPERATION_TRAIT to members(
            "title",
            "summary",
            "description",
            "security",
            "tags",
            "externalDocs",
            "bindings",
        ),
        AsyncApiObjectType.OPERATION_REPLY to members("address", "channel", "messages"),
        AsyncApiObjectType.OPERATION_REPLY_ADDRESS to members("description", "location"),
        AsyncApiObjectType.COMPONENTS to members(
            "schemas",
            "servers",
            "channels",
            "operations",
            "messages",
            "securitySchemes",
            "serverVariables",
            "parameters",
            "correlationIds",
            "replies",
            "replyAddresses",
            "externalDocs",
            "tags",
            "operationTraits",
            "messageTraits",
            "serverBindings",
            "channelBindings",
            "operationBindings",
            "messageBindings",
        ),
        AsyncApiObjectType.MULTI_FORMAT_SCHEMA to members("schemaFormat", "schema"),
        AsyncApiObjectType.SECURITY_SCHEME to members(
            "type",
            "description",
            "name",
            "in",
            "scheme",
            "bearerFormat",
            "flows",
            "openIdConnectUrl",
            "scopes",
        ),
        AsyncApiObjectType.OAUTH_FLOWS to members(
            "implicit",
            "password",
            "clientCredentials",
            "authorizationCode",
        ),
        AsyncApiObjectType.OAUTH_FLOW to members(
            "authorizationUrl",
            "tokenUrl",
            "refreshUrl",
            "availableScopes",
        ),
    )
